[[redirects]]
  from = "/contact"
  to = "/html/contact.html"
  status = 200

[[redirects]]
  from = "/aktuality"
  to = "/html/aktuality.html"
  status = 200

[[redirects]]
  from = "/calendar"
  to = "/html/calendar.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/html/register.html"
  status = 200